# Local Development Configuration (application-dev.properties)

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/tourist_connect?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

# Mail Configuration (Local/Test Credentials)
spring.mail.username=dipaktolangi011@gmail.com
spring.mail.password=oarqrpfqaxtjpwyf

# Khalti Payment Gateway (Test Case)
khalti.secret.key=795c4f9dab7e4f159c9665d44b980e2d

# Fallback for Google (if env variable missing)
google.client.id=159494677752-8jv2mcnb1ei6kgdr5e768d5hji45ki29.apps.googleusercontent.com
