import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precaching assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// 1. Map Tile Caching (Cache First)
// Matches OpenStreetMap tiles: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
registerRoute(
    ({ url }) => url.host.includes('tile.openstreetmap.org') || url.host.includes('tiles.mapbox.com'),
    new CacheFirst({
        cacheName: 'map-tiles',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 500, // Store up to 500 tiles
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
);

// 2. API Response Caching (Stale While Revalidate)
// Matches your backend API endpoints
/* Temporarily disabled API caching as it might interfere with real-time updates and dev environment CORS
registerRoute(
    ({ url }) => url.pathname.startsWith('/api/'),
    new StaleWhileRevalidate({
        cacheName: 'api-responses',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 24 * 60 * 60, // 24 Hours
            }),
            new CacheableResponsePlugin({
                statuses: [200],
            }),
        ],
    })
);
*/

// 3. Static Image Caching (Cache First)
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
