# Common Application Configuration
spring.application.name=TouristConnect

# Profiles
spring.profiles.active=prod

# Fallback for startup stability
google.client.id=${GOOGLE_CLIENT_ID:placeholder}

# JPA/Hibernate Common
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#mail
RESEND_API_KEY=re_ieQede1e_5BHahtrMWwpjDvmuucgDHPoy

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.springframework.mail=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

# Khalti Common
khalti.initiate.url=https://a.khalti.com/api/v2/epayment/initiate/
khalti.lookup.url=https://a.khalti.com/api/v2/epayment/lookup/
khalti.return.url=http://localhost:5173/payment/success
khalti.website.url=http://localhost:5173/
